
name: Ftp publish

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run yarn install
        run: yarn install

      - name: Run yarn build
        run: yarn build

      - name: List output files
        run: ls

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: sftp://sftp.oni.nl
          port: 22
          protocol: sftp
          username: filidorwiese.nl
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: public/
          git-ftp-args: --insecure --remote-root test/
